teb.AspNetCore/teb.AspNetCore/Models/Categoria.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace teb.AspNetCore.Models
{
    public class Categoria
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [StringLength(100)]
        [Required]
        public string Nome { get; set; }

        public List<Produto> Produtos { get; set; }

    }
}

teb.AspNetCore/teb.AspNetCore/Models/ErrorViewModel.cs
using System;

namespace teb.AspNetCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

teb.AspNetCore/teb.AspNetCore/Models/Produto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace teb.AspNetCore.Models
{
    public class Produto
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string Nome { get; set; }

        [Required]
        public decimal Preco { get; set; }

        public string Imagem { get; set; }

        [StringLength(200)]
        public string Descricao { get; set; }

        [Required]
        public int QuantidadeEstoque { get; set; }

        [Required]
        public int CategoriaId { get; set; }

        public virtual Categoria Categoria { get; set; }

    }
}

teb.AspNetCore/teb.AspNetCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using teb.AspNetCore.Models;
using teb.AspNetCore.Repository.Interfaces;
using teb.AspNetCore.ViewModel;

namespace teb.AspNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IProdutoRepository _produtoRepository;

        private readonly ICategoriaRepository _categoriaRepository;

        public HomeController(ILogger<HomeController> logger, IProdutoRepository produtoRepository, ICategoriaRepository categoriaRepository)
        {
            _logger = logger;
            _produtoRepository = produtoRepository;
            _categoriaRepository = categoriaRepository;
        }

        public IActionResult Index()
        {
            var lista = new ListarProdutoViewModel();

            lista.Categorias.AddRange(_categoriaRepository.CarregarTodos());

            lista.Produtos.AddRange(_produtoRepository.CarregarTodos());

            return View(lista);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

teb.AspNetCore/teb.AspNetCore/Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using teb.AspNetCore.Repository.Interfaces;

namespace teb.AspNetCore.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;

        public ProdutosController(IProdutoRepository produtoRepository)
        {
            _produtoRepository = produtoRepository;
        }

        public IActionResult Cervejas()
        {
            var cervejas = _produtoRepository.CarregarProdutosPorCategoria(idCategoria: 1);

            return View(cervejas);
        }
    }
}

teb.AspNetCore/teb.AspNetCore/Views/Home/Index.cshtml
@model ListarProdutoViewModel
@using teb.AspNetCore.ViewModel;

@{
    ViewData["Title"] = "Home Page";
}

@foreach (var categoria in Model.Categorias)
{
    var produtosDaCategoria = Model.Produtos.Where(p => p.CategoriaId == categoria.Id).Take(4).OrderBy(p => p.Nome).ToList();

<div class="row">
    <h2 class="col-12">@categoria.Nome</h2>

    @foreach (var produto in produtosDaCategoria)
    {
        <partial name="_CardProdutoPartial" for="@produto" />
    }

</div>
}

teb.AspNetCore/teb.AspNetCore/Views/Produtos/Cervejas.cshtml
@model List<Produto>
@using teb.AspNetCore.Models;

@{
    ViewData["Title"] = "Cervejas";
}

<div class="row">
    @foreach (var produto in Model)
    {
        <partial name="_CardProdutoPartial" for="@produto" />
    }
</div>

teb.AspNetCore/teb.AspNetCore/Views/Shared/_CardProdutoPartial.cshtml
@model Produto

<div class="col-md-4">
    <figure class="card card-product">
        <div class="img-wrap"><img src="@Model.Imagem"></div>
        <figcaption class="info-wrap">
            <h4 class="title">@Model.Nome</h4>
            <p class="desc">@Model.Descricao</p>
            <div class="rating-wrap">
                <div class="label-rating">@Model.QuantidadeEstoque disponíveis.</div>
            </div> <!-- rating-wrap.// -->
        </figcaption>
        <div class="bottom-wrap">
            <a href="" class="btn btn-sm btn-primary float-right">Adicionar Carrinho</a>
            <div class="price-wrap h5">
                <span class="price-new">R$ @Model.Preco</span>
            </div> <!-- price-wrap.// -->
        </div> <!-- bottom-wrap.// -->
    </figure>
</div> <!-- col // -->

teb.AspNetCore/teb.AspNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Home</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">No trabalho.</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Cervejas">Cervejas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - teb.AspNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>